oauth2:
  user:
    google:
      clientId: 
      clientSecret: 
      redirect-uri: http://localhost:8080/oauth2/callback/google
    naver:
      clientId: 
      clientSecret: 
      redirect-uri: http://localhost:8080/oauth2/callback/naver
    kakao:
      clientId: 
      clientSecret: 
      redirect-uri: http://localhost:8080/oauth2/callback/kakao
  provider:
    google:
      authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    naver:
      authorization-uri: https://nid.naver.com/oauth2.0/authorize
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
    kakao:
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me

