spring:

  datasource:
    url: jdbc:mysql://mysql:3306/backend
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

---

spring:

  config:
    activate:
      on-profile: db-local

  datasource:
    username: root
    password: 12345678@

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

---

spring:

  config:
    activate:
      on-profile: db-dev

  datasource:
    username: root
    password: g27no795h8pce4YFdbmD

  jpa:
    hibernate:
      ddl-auto: update
