spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

jwt:
  accessSecretKey: ${JWT_ACCESS_SECRET_KEY}
  refreshSecretKey: ${JWT_REFRESH_SECRET_KEY}


oauth2:
  user:
    google:
      clientId: 301049816046-1slb1riih6jvp420kqrerhph5upp5atj.apps.googleusercontent.com
      clientSecret: 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
      redirect-uri: http://localhost:8080/oauth2/callback/google
    naver:
      clientId: 0r7QyOW6Nbojtet0uqPv
      clientSecret: 8Bki4LOoGB
      redirect-uri: http://localhost:8080/oauth2/callback/naver
    kakao:
      clientId: 7829bb416bd43005e3bf972a5bf240dc
      clientSecret: trhP8ptxsW2bNwjn5FJhosUybVlvNGly
      redirect-uri: http://localhost:8080/oauth2/callback/kakao
  provider:
    google:
      authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    naver:
      authorization-uri: https://nid.naver.com/oauth2.0/authorize
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
    kakao:
      authorization-uri: https://kauth.kakao.com/oauth/authorize
      token-uri: https://kauth.kakao.com/oauth/token
      user-info-uri: https://kapi.kakao.com/v2/user/me

