name: Build and Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Push Docker Images
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker build -t ${{ secrets.DOCKER_REPO }}/tdwork-api-server
        docker push ${{ secrets.DOCKER_REPO }}/tdwork-nginx

    - name: Upload docker-compose.yml
      uses: actions/upload-artifact@v3
      with:
        name: docker-compose
        path: ./docker-compose.yml
 
  deploy:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Download docker-compose.yml
        uses: actions/download-artifact@v3
        with:
          name: docker-compose

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: SCP transfer
        run: scp ./docker-compose.yml ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/

      - name: Execute remote commands
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "sudo docker rm -f $(docker ps -qa)"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "sudo docker pull ${{ secrets.DOCKER_REPO }}/tdwork-api-server"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "sudo docker pull ${{ secrets.DOCKER_REPO }}/tdwork-nginx"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker-compose up -d"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker image prune -f"