name: Build and Deploy to Dev server

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile.dev
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tdwork-api-server:latest
        cache-from: type=gha
        cache-to: type=gha, mode=max

    - name: Upload docker-compose.dev.yml
      uses: actions/upload-artifact@v3
      with:
        name: docker-artifact
        path: |
          docker-compose.dev.yml
          .platform
 
  deploy:
    needs:
      - build

    runs-on: ubuntu-latest

    steps:
      - name: Download docker-compose.dev.yml
        uses: actions/download-artifact@v3
        with:
          name: docker-artifact
          path: ./

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: SCP transfer
        run: |
          scp ./docker-compose.dev.yml ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/docker-compose.yml
          scp -r .platform ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/ 


      - name: Execute remote commands
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "sudo docker pull ${{ secrets.DOCKER_REPO }}/tdwork-api-server"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker-compose up --build -d"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "docker image prune -a -f"